apiVersion: v1
kind: Service

metadata:
  name: node-svc
  namespace: default

spec:
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 3000

  selector:
    app: node

  type: NodePort

# apiVersion: v1
# kind: Service
# metadata:
#   name: node-service
# spec:
#   selector:
#     app: node
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3000
#   type: LoadBalancer